### ISSUE TITLE
onDeepLinking not called on flutter IOS

### ISSUE THREAD

**Issue by skripsimu** [AppsFlyerSDK/appsflyer-flutter-plugin#142] opened 2021-07-19 06:18 UTC
-Appsflyer_sdk: ^6.3.2-nullsafety.0
- Apps is installed
- Device IOs 14.6
- Is the app being opened in the background

this function is not called on IOs :
afSdk.onDeepLinking((res) {});

but the log from native send this
AppsFlyer [deep link]: continue userActivity
[Shortlink] OneLink:{
    "af_ad" = flutter;
    "af_adset" = "mobile_apps";
[Shortlink] Response Info:{
    data = {length = 706, bytes = 0x7b227574 6d5f636f 6e74656e 74223a22 ... 655f6170 7073227d };
    dataStr = "{\"utm_content\":\"mobile_apps\",\"is_retargeting\":\"true\",\"utm_source\":\"flutter\",\"af_android_url\":\"
[Shortlink] Error: (null)
[DEBUG] AppsFlyer: [DDL] Calling didResolveDeepLink with: {"af_sub4":null,"click_http_referrer":null,"af_sub1":null,"click_event":{"utm_term":"flutter_redirect","utm_source":"flutter","utm_content":"mobile_apps","utm_medium":"dart","utm_campaign":"flutter_mobile","campaign":"Tested","media_source":"onelink_url"},"af_sub3":null,"deep_link_value":null,"campaign":"Tested","match_type":null,"af_sub5":null,"media_source":"onelink_url","campaign_id":null,"af_sub2":null}   

can you help me?

**Comment by supposedlysam-bb** [comment] 2021-07-19 21:53
I'm also experiencing this issue

My log says, `AppsFlyer Debug: handle deep link` but then doesn't deep link into my code.

### AppDelegate.swift
```swift
import UIKit
import Flutter

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    if #available(iOS 10.0, *) {
      UNUserNotificationCenter.current().delegate = self
    }
    GeneratedPluginRegistrant.register(with: self)
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }

  // Begin appsflyer_sdk integration
  override func application(_ application: UIApplication, open url: URL, sourceApplication: String?, annotation: Any) -> Bool {
    AppsFlyerAttribution.shared()!.handleOpenUrl(url, sourceApplication: sourceApplication, annotation: annotation);
    return true
  }

  override func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:]) -> Bool {
    AppsFlyerAttribution.shared()!.handleOpenUrl(url, options: options)
    return true
  }

  private func application(_ application: UIApplication, continue userActivity: NSUserActivity, restorationHandler: @escaping ([Any]?) -> Void) -> Bool {
    AppsFlyerAttribution.shared()!.continueUserActivity(userActivity, restorationHandler: nil)
    return true
  }

  override func application(_ application: UIApplication, continue userActivity: NSUserActivity, restorationHandler: @escaping ([UIUserActivityRestoring]?) -> Void) -> Bool {
    AppsFlyerAttribution.shared()!.continueUserActivity(userActivity, restorationHandler: nil)
    return true
  }
  // End appsflyer_sdk integration
}
```

### Runner-Bridging-Header.h
```objective-c
#import "GeneratedPluginRegistrant.h"
#import "AppsflyerSdkPlugin.h"

```

on Android, the deep link opens correctly when the app is closed.

However on iOS, only the installConversion event gets through to my code.

**Comment by supposedlysam-bb** [comment] 2021-07-19 22:54
I enabled debug mode and also added some additional logs. Here's what I've found so far: 

### Deep Link: Closed App

<details><summary>Logs from Console</summary>
<p>

```txt
default	16:45:02.428229-0600	Blue Bottle Prod	AppsFlyer [deep link]: continue userActivity
default	16:45:02.428283-0600	Blue Bottle Prod	AppsFlyer Debug: continueUserActivity: bridge is not ready
default	16:45:02.576546-0600	Blue Bottle Prod	[DEBUG] AppsFlyer: * AppsFlyer is set to debug mode. This should only be used in development environment! *
default	16:45:02.576700-0600	Blue Bottle Prod	[DEBUG] AppsFlyer: ASIdentifierManager loaded
default	16:45:02.576750-0600	Blue Bottle Prod	[DEBUG] AppsFlyer: ADClient not found
default	16:45:02.576800-0600	Blue Bottle Prod	[DEBUG] AppsFlyer: CTTelephonyNetworkInfo loaded
default	16:45:02.576853-0600	Blue Bottle Prod	[DEBUG] AppsFlyer: FBSDKAppEventsUtility not found
default	16:45:02.576900-0600	Blue Bottle Prod	AppsFlyer Debug: handle deep link
default	16:45:02.583595-0600	Blue Bottle Prod	[DEBUG] AppsFlyer: [CACHE] Cache path: /var/mobile/Containers/Data/Application/A0B0822C-92C9-45B3-A06C-DA96DBB31992/Library/Caches/appsflyer-v1
default	16:45:02.583858-0600	Blue Bottle Prod	[DEBUG] AppsFlyer: [DDL] Delegate: AppsFlyerStreamHandler
default	16:45:02.584211-0600	Blue Bottle Prod	[DEBUG] AppsFlyer: [DDL] DDL already has been resolved
default	16:45:02.584399-0600	Blue Bottle Prod	[DEBUG] AppsFlyer: Start
default	16:45:02.584593-0600	Blue Bottle Prod	[DEBUG] AppsFlyer: isFirstLaunch: No, timestamp: 1626734289.627680
default	16:45:02.584789-0600	Blue Bottle Prod	[DEBUG] AppsFlyer: First `start` since application termintaion/installation
default	16:45:02.584923-0600	Blue Bottle Prod	[DEBUG] AppsFlyer: `appsFlyerDevKey`: y5*****5C
default	16:45:02.590400-0600	Blue Bottle Prod	[DEBUG] AppsFlyer: Looking for previous version date
default	16:45:02.590502-0600	Blue Bottle Prod	[DEBUG] AppsFlyer: Current cached application version: 1.0.0, new version: 1.0.0
default	16:45:02.590553-0600	Blue Bottle Prod	[DEBUG] AppsFlyer: Use date3 from storage
default	16:45:02.590701-0600	Blue Bottle Prod	[DEBUG] AppsFlyer: date1: 2021-07-19_163753-0600
default	16:45:02.590749-0600	Blue Bottle Prod	[DEBUG] AppsFlyer: date2: 2021-07-19_164502-0600
default	16:45:02.590796-0600	Blue Bottle Prod	[DEBUG] AppsFlyer: date3: 2021-07-19_163809-0600
default	16:45:02.590898-0600	Blue Bottle Prod	[DEBUG] AppsFlyer: First launch date: 2021-07-19_163809-0600
default	16:45:02.592758-0600	Blue Bottle Prod	[DEBUG] AppsFlyer: iAD: iSearchAdsDict is nil
default	16:45:02.593415-0600	Blue Bottle Prod	[DEBUG] AppsFlyer: [SKAd] Loaded configuration: 4
default	16:45:02.593583-0600	Blue Bottle Prod	[DEBUG] AppsFlyer: Dynamically loaded library: AppTrackingTransparency
default	16:45:02.599061-0600	Blue Bottle Prod	[DEBUG] AppsFlyer: IDFA disabled
default	16:45:02.605568-0600	Blue Bottle Prod	[DEBUG] AppsFlyer: ASIdentifierManager loaded
default	16:45:02.606144-0600	Blue Bottle Prod	[DEBUG] AppsFlyer: ADClient not found
default	16:45:02.606194-0600	Blue Bottle Prod	[DEBUG] AppsFlyer: CTTelephonyNetworkInfo loaded
default	16:45:02.606297-0600	Blue Bottle Prod	[DEBUG] AppsFlyer: FBSDKAppEventsUtility not found
default	16:45:02.606528-0600	Blue Bottle Prod	[DEBUG] AppsFlyer: Start
default	16:45:02.606806-0600	Blue Bottle Prod	[DEBUG] AppsFlyer: isFirstLaunch: No, timestamp: 1626734289.627680
default	16:45:02.606909-0600	Blue Bottle Prod	[DEBUG] AppsFlyer: Time from last launch(session) 0.016755
default	16:45:02.607260-0600	Blue Bottle Prod	[DEBUG] AppsFlyer: Skip launch
default	16:45:02.609018-0600	Blue Bottle Prod	[DEBUG] AppsFlyer: [CACHE] Caching request...(cache size: 0)
default	16:45:02.611325-0600	Blue Bottle Prod	[DEBUG] AppsFlyer: [HTTP] Operation start: `288-1626734702.501700`
default	16:45:02.612806-0600	Blue Bottle Prod	[DEBUG] AppsFlyer: 

<~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~~+~>
<~+~   SEND Start:   https://launches.appsflyer.com/api/v6.2/iosevent?app_id=1440573734&buildnumber=6.2.4
<~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~~+~>

{"cell":{"mcc":"310","mnc":"260","ra":"CTRadioAccessTechnologyLTE"},"uid":"1626734273146-9469351","bundlename":"","platformextension":"ios_segment","timestamp":"1626734702.501700","att_status":0,"platform":"iPhone11,8","counter":"4","prev_session_dur":135,"sk_rules":{"sk_exp":1626820690.9143341,"sk_rules":{"wi":24,"ex":1,"di":1}},"reinstallCounter":"22","onelink_id":null,"advertiserId":"","systemversion":"14.6","iaecounter":"0","lang_code":"en","JBDevice":false,"date3":"2021-07-19_163809-0600","deviceData":{"cpu_type":"ARM64","cpu_speed":"-1","osVersion":"14.6 (Build 18F72)","ram_size":"2845","cpu_64bits":"true","dim":{"y_px":1792,"x_px":828},"device_model":"iPhone11,8","cpu_count":"6"},"sc_o":"fu","open_referrer":"","currentCountrycode":"US","systemname":"iOS","date1":"2021-07-19_163753-0600","<…>
default	16:45:02.723767-0600	Blue Bottle Prod	[DEBUG] AppsFlyer: [HTTP] 
Result: {
    data = {length = 2, bytes = 0x6f6b};
    dataStr = ok;
    retries = 2;
    statusCode = 200;
    taskIdentifier = 2;
}                
Error: (null)
default	16:45:02.723848-0600	Blue Bottle Prod	[DEBUG] AppsFlyer: Loading conversion data
default	16:45:02.724092-0600	Blue Bottle Prod	[DEBUG] AppsFlyer: [GCD-A02] -[AppsFlyerStreamHandler onConversionDataSuccess:]:
{
    "af_message" = "organic install";
    "af_status" = Organic;
    "install_time" = "2021-07-19 22:42:30.751";
    "is_first_launch" = 0;
}
default	16:45:02.724339-0600	Blue Bottle Prod	flutter: flutter-appsflyer: callListener onInstallConversionData
default	16:45:02.724944-0600	Blue Bottle Prod	[DEBUG] AppsFlyer: [CACHE] Deleting file: /var/mobile/Containers/Data/Application/A0B0822C-92C9-45B3-A06C-DA96DBB31992/Library/Caches/appsflyer-v1/648427502.5215.plist
default	16:45:02.727257-0600	Blue Bottle Prod	[DEBUG] AppsFlyer: [CACHE] Error deleting file: /var/mobile/Containers/Data/Application/A0B0822C-92C9-45B3-A06C-DA96DBB31992/Library/Caches/appsflyer-v1/648427502.5215.plist, “648427502.5215.plist” couldn’t be removed.
default	16:45:02.727323-0600	Blue Bottle Prod	[DEBUG] AppsFlyer: [HTTP] Dealloc. Time elapsed for: `288-1626734702.501700` - 0.2038038969039917

```

</p></details>

### Deep Link: App Backgrounded
<details><summary>Logs from Console</summary>
<p>

```txt
default	16:42:48.471316-0600	Blue Bottle Prod	AppsFlyer [deep link]: continue userActivity
default	16:42:48.471508-0600	Blue Bottle Prod	AppsFlyer Debug: continueUserActivity: bridge is ready
default	16:42:48.471560-0600	Blue Bottle Prod	[DEBUG] AppsFlyer: NSUserActivity `webpageURL`: https://applink.bluebottlecoffee.com/KUbj/343fd344
default	16:42:48.472793-0600	Blue Bottle Prod	[DEBUG] AppsFlyer: Deeplink regex execution time: 0.000032
default	16:42:48.473381-0600	Blue Bottle Prod	[DEBUG] AppsFlyer: [HTTP] Operation start: `OneLink-C38CA621-D7CF-4692-A4D7-EB2C9CFE7E73`
default	16:42:48.474280-0600	Blue Bottle Prod	[DEBUG] AppsFlyer: UniversalLink/Deeplink found:
https://applink.bluebottlecoffee.com/KUbj/343fd344
default	16:42:48.475395-0600	Blue Bottle Prod	[DEBUG] AppsFlyer: Validate custom domain URLs: (
    "applink.bluebottlecoffee.com"
)
default	16:42:48.476744-0600	Blue Bottle Prod	[DEBUG] AppsFlyer: Shortlink found. Executing: https://onelink.appsflyer.com/shortlink-sdk/v1/KUbj?id=343fd344
default	16:42:48.485740-0600	Blue Bottle Prod	[DEBUG] AppsFlyer: [HTTP] Dealloc. Time elapsed for: `OneLink-C38CA621-D7CF-4692-A4D7-EB2C9CFE7E73` - 0.007930994033813477
default	16:42:48.614806-0600	Blue Bottle Prod	[DEBUG] AppsFlyer:                        
[Shortlink] OneLink:{
    "af_lp_src" = "https://creatives-cdn.appsflyer.com/crt-936ccf2d-12dd-4aa5-9d3c-c3d660be8da91";
    branch = 1167;
    c = "Developer Test Campaign";
    campaign = "Developer Test Campaign";
    "media_source" = "QR_code";
    pid = "QR_code";
    product = 78;
}                       
[Shortlink] Response Info:{
    data = {length = 232, bytes = 0x7b227069 64223a22 51525f63 6f646522 ... 525f636f 6465227d };
    dataStr = "{\"pid\":\"QR_code\",\"c\":\"Developer Test Campaign\",\"product\":\"78\",\"branch\":\"1167\",\"af_lp_src\":\"https://creatives-cdn.appsflyer.com/crt-936ccf2d-12dd-4aa5-9d3c-c3d660be8da91\",\"campaign\":\"Developer Test Campaign\",\"media_source\":\"QR_code\"}";
    retries = 0;
    statusCode = 200;
    taskIdentifier = 11;
}                       
[Shortlink] Error: (null)
default	16:42:48.616000-0600	Blue Bottle Prod	flutter: flutter-appsflyer: callListener onDeepLinking
default	16:42:48.913315-0600	Blue Bottle Prod	[DEBUG] AppsFlyer: ASIdentifierManager loaded
default	16:42:48.917211-0600	Blue Bottle Prod	[DEBUG] AppsFlyer: ADClient not found
default	16:42:48.917292-0600	Blue Bottle Prod	[DEBUG] AppsFlyer: CTTelephonyNetworkInfo loaded
default	16:42:48.917341-0600	Blue Bottle Prod	[DEBUG] AppsFlyer: FBSDKAppEventsUtility not found
default	16:42:48.917495-0600	Blue Bottle Prod	[DEBUG] AppsFlyer: Start
default	16:42:48.920443-0600	Blue Bottle Prod	[DEBUG] AppsFlyer: isFirstLaunch: No, timestamp: 1626734289.627680
default	16:42:48.921025-0600	Blue Bottle Prod	[DEBUG] AppsFlyer: Time from last launch(session) 4.911302
default	16:42:48.921117-0600	Blue Bottle Prod	[DEBUG] AppsFlyer: Skip launch
```

</p></details>

Hope this helps to diagnose!

**Comment by pazlavi** [comment] 2021-07-26 15:21
Hi @skripsimu  and @supposedlysam-bb, 
Thank you for reaching out to us. 

Did you debug your app using breakpoints and make sure that the callback is not called at all? 
Maybe you tried to get some value from the map and got a null object? Currently, the map returned in the callback is not identical in both OS. 
Please feel free to contact our support team at support@appsflyer.com for additional assistant. When submitting an issue, please specify your AppsFlyer sign-up (account) email, your app ID, reproduction steps, logs, code snippets, and any additional relevant information.

**Comment by supposedlysam-bb** [comment] 2021-07-28 21:40
> Hi @skripsimu and @supposedlysam-bb,
> Thank you for reaching out to us.
> 
> Did you debug your app using breakpoints and make sure that the callback is not called at all?
> Maybe you tried to get some value from the map and got a null object? Currently, the map returned in the callback is not identical in both OS.
> Please feel free to contact our support team at [support@appsflyer.com](mailto:support@appsflyer.com) for additional assistant. When submitting an issue, please specify your AppsFlyer sign-up (account) email, your app ID, reproduction steps, logs, code snippets, and any additional relevant information.

Hey @pazlavi, thanks for your response. I have debugged the app using breakpoints. However, the logs that I provided also has a label of `flutter: flutter-appsflyer:` where you can see what calls were being made. 

If you take a look at the logs above, you can see that when the app is backgrounded it calls `onDeepLinking` (correctly), but when the app is closed and then opened from a deep link, only the `onInstallConversionData` is being called.

I'm expecting for `onDeepLinking` to be called in both scenarios.

Note: I am handling the different objects appropriately in my Flutter code.

I'm using the `appsflyer_sdk: 6.2.4+1-flutterv1` in case that helps. This is the latest version I can use since we haven't upgraded to dart sdk 2.12 yet.

Would you mind verify my findings?

**Comment by pazlavi** [comment] 2021-07-28 22:17
Hi @supposedlysam-bb, 

Thank you for the response.

Based on your version, it seems like your issue is related to [this issue ](https://github.com/AppsFlyerSDK/appsflyer-flutter-plugin/issues/126) #126.
We had the same issue with our Cordova plugin as well. You can find it [here](https://github.com/AppsFlyerSDK/appsflyer-cordova-plugin/issues/167) .

All you need to do is replacing your [current](https://github.com/AppsFlyerSDK/appsflyer-flutter-plugin/blob/v6.2.4+1-flutterv1/ios/Classes/AppsFlyerAttribution.m) `AppsFlyerAttribution.m` file with the [latest one](https://github.com/AppsFlyerSDK/appsflyer-flutter-plugin/blob/master/ios/Classes/AppsFlyerAttribution.m) (from the master branch )

**Comment by supposedlysam-bb** [comment] 2021-07-29 16:29
Unfortunately switching out the class is not possible. The `AppsFlyerAttribution.m` file is located in the code that's pulled in from the plugin. This cannot be changed locally as our CI would just get the package from the pub again (without our local changes). 

Thanks for letting me know it's fixed in a later version. We'll just have to wait until we upgrade our project to null safety before we can pull in the latest version.

**Comment by digocse** [comment] 2021-08-30 19:39
I updated to the newest version `^6.3.5+1` and we're experiencing the same behavior here. Only `onInstallConversionData` is being called with `deep_link_value` and `deep_link_sub1` values within it.

Any updates?

**Comment by pazlavi** [comment] 2021-08-31 08:07
Hi @digocse 
To provide optimal support, we would kindly ask you to submit a support ticket to support@appsflyer.com.

When submitting the ticket, please specify your AppsFlyer sign-up (account) email, app ID, reproduction steps, code snippets, logs, the links you used, and any additional relevant information.

**Comment by pierrea** [comment] 2021-09-14 13:06
Hi there, just signaling that I'm experiencing the issue as well, and contacted Support. 
Hopefully it gets addressed soon. Much appreciated!

**Comment by digocse** [comment] 2021-09-15 14:45
> Hi there, just signaling that I'm experiencing the issue as well, and contacted Support.
> 
> For what it's worth, the `showDebug` option set to `true` doesn't seem to print more logs on iOS. On Android, I'm getting logs regarding `onDeepLinking` being fired.
> 
> Hopefully it gets addressed soon. Much appreciated!

Hey @pierrea!

I was able to make the `onDeepLinking` callback get triggered by setting `af_force_deeplink` as an additional parameter at the AppsFlyer interface with the value `true`.

I'm struggling right now with `onGenerateRoute` not being triggered on iOS while opening a deep link.

Anyhow, hope that the parameter above make it work for you. :)

**Comment by skripsimu** [comment] 2021-09-15 15:01
In my case, the problem solved after updating to appsflyer_sdk: ^6.3.5+3

**Comment by pierrea** [comment] 2021-09-16 12:26
@skripsimu I upgraded appsflyer_sdk to 6.3.5+3 as well but still getting no `onDeepLinking` callback fired on iOS (still working fine on Android). Intriguing!

@digocse Thanks for the tip, but same, although I set `af_force_deeplink` to true as a custom parameter. Even more intriguing as to why it worked for you...
Also, I noticed this `af_force_deeplink` parameter doesn't appear in the payload, although any other custom parameter name does (I tried with `af_test` or whatever).

Such strangeness. I'm still stuck with this issue here.

---
@digocse My way to redirect to a screen is by doing the following (it works on Android but again, not on iOS since I'm not receiving the event):
1. in a singleton class, listen to `onDeepLinking` at the moment of initializing the sdk
```
_appsflyerSdk.onDeepLinking((res) {
  _handleDeepLinkRedirection(res);
});
```
2. since we need a `BuildContext` instance to call Navigator's `push` methods, keep an instance of `context` as an attribute of this singleton class. If `context` hasn't been set yet, "wait" until it is set by saving the deep link's json in another attribute of this class. If `context` already exists, proceed to the redirection.
3. each time a screen is loaded, set the `context` attribute and check if there's already a deep link json to be processed or not. If so, proceed to the redirection.

If there's a better approach, I'd love to hear it!

**Comment by pierrea** [comment] 2021-09-23 16:41
🆙 
Any other workaround suggestions from the team?

**Comment by e-papa** [comment] 2021-10-06 11:14
I'm experiencing the same issues described by @pierrea and @digocse and tried their approaches, which works on Android but not on iOS, no matter what version of the AppsFlyer sdk is being used (6.3.0-6.4.0).

On iOS the `onGenerateRoute` method is not called as @digocse already pointed out.

Any news?

**Comment by pierrea** [comment] 2021-10-07 08:57
I have good hopes the latest v[6.4.0](https://github.com/AppsFlyerSDK/appsflyer-flutter-plugin/pull/159/files) by @GM-appsflyer fixes our problem. Will report back as soon as testing is done on my end 🖖

**Closed** 2021-12-01 08:42 UTC
Labels: bug, waiting for customer response, Platform:iOS

**Comment by e-papa** [comment] 2022-02-15 10:32
@wandriputra try to update Flutter to version `2.8.1`, that seems to have solved issue

**Comment by spegoraro** [comment] 2022-10-11 02:39
FWIW: I'm also seeing this exact behaviour.

Flutter 3.3.4
Dart: 2.18.2
